services:
  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 9999:9999
    depends_on:
      - api1
      - api2
    networks:
      - api
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "20MB"

  api1: &api
    build: .
    environment:
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    depends_on:
      - redis
    networks:
      - api
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "95MB"

  api2:
    <<: *api
    environment:
      - MASTER=true
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080

  api3:
    <<: *api

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - api
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "40MB"

networks:
  api:
    driver: bridge
  payment-processor:
    external: true
